export const ROUTESNAMES = {
  home: "",
  videos: "videos",
  marketPlace: "market_place",
  groups: "groups",
  games: "games",
  profile: "profile",
  firends: "firends",
  memories: "memories",
  saved: "saved",
  feeds: "feeds",
  events: "events",
  messenger: "messenger",
  messengerKids: "messenger_kids",
  birthdays: "birthdays",
  reels: "reels",
  gamingVideos: "gaming_videos",
  playGames: "play_games",
} as const;
